### ISSUE TITLE
loading instance from file

### ISSUE THREAD

**Issue by santoshv** [ConstrainedSampler/PolytopeSamplerMatlab#11]
need example of loading instance from a .m or .mat file in demo.m

**Comment by YinTat** [comment]
The reason I remove that is that the format of .mat is not standard, it is come up with me. (It is not the same format as cobra). So, I don't think demoing is useful.

**Comment by santoshv** [comment]
Is there an easy way for them to input one of theor models? I am worried if that will slow them down. Should we include a simple model like recon1?

-santosh

On Oct 5, 2020, at 1:31 PM, YinTat <notifications@github.com> wrote:

﻿

The reason I remove that is that the format of .mat is not standard, it is come up with me. (It is not the same format as cobra). So, I don't think demoing is useful.
