### ISSUE TITLE
Sample f = x(1-x) on [0,1]

### ISSUE THREAD

**Issue by hjiaa** [ConstrainedSampler/PolytopeSamplerMatlab#46]
I am trying to sample f(x) = x(1-x) on [0,1]. The histogram of the samples does not match the pdf plot.

Here's the code I am using.
```
m = [1,1;0,0];
d = size(m,1);
P = struct;
P.Aineq = [];
P.bineq = [];
P.lb = zeros(d, 1);
P.ub = ones(d, 1);
P.f = @(x) -sum(m(:,1).*log(x)+m(:,2).*log(1-x));
P.df = @(x) -(m(:,1)./x - (m(:,2)./(1-x)));
P.ddf = @(x) (m(:,1)./(x.^2) + (m(:,2)./((1-x).^2))); 

o = sample(P, 20000);

figure;
histogram(o.samples(1,:), 'Normalization', 'pdf')
hold on
x = 0:0.01:1;

a = 1;
b = 1;
f = x.^a .* (1-x).^b / integral(@(x) x.^a .* (1-x).^b, 0, 1);
plot(x,f,'LineWidth',1.5)
hold off
```

And the plot I got:
![beta_plot](https://github.com/ConstrainedSampler/PolytopeSamplerMatlab/assets/15610305/d9f05fb7-ad30-4dbd-8cf8-3492ddee7fc7)

**Comment by ehidalgo8gatech** [comment]
This has been resolved --- there was a bug in checking for the P.ddf field in the input. Thank you.

**Comment by santoshv** [comment]
This has been resolved. There was a bug in checking the input for P.ddf. Thank you.
