### ISSUE TITLE
standard Gaussian on netlib/agg

### ISSUE THREAD

**Issue by YinTat** [ConstrainedSampler/PolytopeSamplerMatlab#5]
The program converges to take step size 0.

**Comment by santoshv** [comment]
This is currently if Gaussian center is outside polyhedron. Then step size can become too small. This needs program/algorithm enhancement!

**Comment by YinTat** [comment]
Maybe we should have various tests for non-uniform distribution. Then we can try to fix it after creating the tests.

Put the test to coverage folder. We can organize it later. That folder is not very organized now.

@santoshv
